"""
Strategy Agent

Analyzes market data to generate trading signals using AI/LLM.
Responsible for:
- Signal generation for CEX trading
- Arbitrage opportunity detection
- Polymarket prediction analysis
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Optional
import logging
import json

from app.core.config import settings
from app.services.ai.data_aggregator import AggregatedMarketData, TechnicalIndicators

logger = logging.getLogger(__name__)


class SignalType(str, Enum):
    """Type of trading signal"""
    LONG = "long"
    SHORT = "short"
    HOLD = "hold"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"


class SignalStrength(str, Enum):
    """Signal strength classification"""
    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"


class MarketType(str, Enum):
    """Market type for signal - Platform supports spot trading only"""
    CEX_SPOT = "cex_spot"
    # CEX_FUTURES = "cex_futures"  # Not supported - spot trading only
    POLYMARKET = "polymarket"


@dataclass
class TradingSignal:
    """Trading signal generated by strategy agent"""
    signal_id: str
    timestamp: datetime
    
    # Signal details
    symbol: str
    market_type: MarketType
    signal_type: SignalType
    strength: SignalStrength
    
    # Confidence and reasoning
    confidence: float  # 0-1
    reasoning: str
    
    # Price targets
    entry_price: Decimal
    stop_loss: Decimal
    take_profit: Decimal
    
    # Position sizing suggestion
    suggested_position_pct: float
    risk_reward_ratio: float
    
    # Time validity
    valid_until: datetime
    
    # Additional data
    indicators_snapshot: dict = field(default_factory=dict)
    market_context: dict = field(default_factory=dict)
    
    def to_dict(self) -> dict:
        return {
            "signal_id": self.signal_id,
            "timestamp": self.timestamp.isoformat(),
            "symbol": self.symbol,
            "market_type": self.market_type.value,
            "signal_type": self.signal_type.value,
            "strength": self.strength.value,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "entry_price": float(self.entry_price),
            "stop_loss": float(self.stop_loss),
            "take_profit": float(self.take_profit),
            "suggested_position_pct": self.suggested_position_pct,
            "risk_reward_ratio": self.risk_reward_ratio,
            "valid_until": self.valid_until.isoformat(),
            "indicators_snapshot": self.indicators_snapshot,
            "market_context": self.market_context
        }


@dataclass
class ArbitrageOpportunity:
    """Arbitrage opportunity detected"""
    opportunity_id: str
    timestamp: datetime
    
    # Markets involved
    market_a: str
    market_b: str
    
    # Prices
    price_a: Decimal
    price_b: Decimal
    spread_pct: float
    
    # Expected profit
    expected_profit_pct: float
    confidence: float
    
    # Execution details
    recommended_size: Decimal
    estimated_fees: Decimal
    net_profit_pct: float
    
    # Validity
    valid_until: datetime


class StrategyAgent:
    """
    Strategy Agent for generating trading signals.
    Uses technical analysis and LLM for decision making.
    """
    
    def __init__(self):
        self._llm_client = None  # Would be initialized with OpenRouter/OpenAI
        self._signal_history: list[TradingSignal] = []
        self._active_signals: dict[str, TradingSignal] = {}
    
    async def initialize(self) -> None:
        """Initialize LLM client and load configuration"""
        # Initialize LLM client
        api_key = settings.ai.openrouter_api_key.get_secret_value()
        if not api_key:
            api_key = settings.ai.openai_api_key.get_secret_value()
        
        if api_key:
            logger.info("LLM client configured")
        else:
            logger.warning("No LLM API key configured, using rule-based strategy only")
    
    async def analyze_market(
        self,
        market_data: AggregatedMarketData,
        market_type: MarketType = MarketType.CEX_SPOT
    ) -> Optional[TradingSignal]:
        """
        Analyze market data and generate trading signal.
        
        Args:
            market_data: Aggregated market data
            market_type: Type of market to analyze
            
        Returns:
            TradingSignal if conditions are met, None otherwise
        """
        logger.info(f"Analyzing market for {market_data.symbol}")
        
        # Step 1: Rule-based pre-screening
        pre_screen = self._pre_screen_opportunity(market_data)
        if not pre_screen["has_opportunity"]:
            logger.debug(f"No opportunity detected for {market_data.symbol}")
            return None
        
        # Step 2: Technical analysis scoring
        ta_score = self._calculate_ta_score(market_data.indicators)
        
        # Step 3: Sentiment analysis (if available)
        sentiment_score = 0.0
        if market_data.sentiment:
            sentiment_score = market_data.sentiment.overall_sentiment
        
        # Step 4: Combine scores
        combined_score = (ta_score * 0.6) + (sentiment_score * 0.2) + (pre_screen["score"] * 0.2)
        
        # Step 5: Generate signal if score exceeds threshold
        if abs(combined_score) < 0.3:  # Threshold for generating signal
            return None
        
        # Step 6: Use LLM for final analysis (if configured)
        llm_analysis = await self._llm_analyze(market_data, ta_score, sentiment_score)
        
        # Step 7: Generate signal
        signal = self._create_signal(
            market_data=market_data,
            market_type=market_type,
            combined_score=combined_score,
            ta_score=ta_score,
            sentiment_score=sentiment_score,
            llm_analysis=llm_analysis
        )
        
        if signal:
            self._active_signals[signal.signal_id] = signal
            self._signal_history.append(signal)
        
        return signal
    
    def _pre_screen_opportunity(
        self,
        market_data: AggregatedMarketData
    ) -> dict[str, Any]:
        """Pre-screen for trading opportunities using basic rules"""
        score = 0.0
        reasons = []
        
        indicators = market_data.indicators
        
        # RSI check
        if indicators.rsi_14:
            if indicators.rsi_14 < 30:
                score += 0.3
                reasons.append("RSI oversold")
            elif indicators.rsi_14 > 70:
                score -= 0.3
                reasons.append("RSI overbought")
        
        # Price vs moving averages
        price = float(market_data.current_price)
        
        if indicators.sma_20 and indicators.sma_50:
            if price > indicators.sma_20 > indicators.sma_50:
                score += 0.2
                reasons.append("Bullish MA alignment")
            elif price < indicators.sma_20 < indicators.sma_50:
                score -= 0.2
                reasons.append("Bearish MA alignment")
        
        # MACD
        if indicators.macd_histogram:
            if indicators.macd_histogram > 0 and indicators.macd > indicators.macd_signal:
                score += 0.2
                reasons.append("Bullish MACD")
            elif indicators.macd_histogram < 0 and indicators.macd < indicators.macd_signal:
                score -= 0.2
                reasons.append("Bearish MACD")
        
        # Bollinger Band position
        if indicators.bollinger_lower and indicators.bollinger_upper:
            if price < indicators.bollinger_lower:
                score += 0.15
                reasons.append("Below lower Bollinger Band")
            elif price > indicators.bollinger_upper:
                score -= 0.15
                reasons.append("Above upper Bollinger Band")
        
        # Volume confirmation
        if indicators.volume_sma_20:
            volume_ratio = float(market_data.volume_24h) / indicators.volume_sma_20 / 24
            if volume_ratio > 1.5:
                score *= 1.2
                reasons.append("High volume confirmation")
        
        return {
            "has_opportunity": abs(score) > 0.2,
            "score": score,
            "reasons": reasons
        }
    
    def _calculate_ta_score(self, indicators: TechnicalIndicators) -> float:
        """Calculate composite technical analysis score"""
        score = 0.0
        weights = 0.0
        
        # RSI contribution (-1 to 1)
        if indicators.rsi_14:
            if indicators.rsi_14 < 30:
                rsi_score = (30 - indicators.rsi_14) / 30
            elif indicators.rsi_14 > 70:
                rsi_score = (70 - indicators.rsi_14) / 30
            else:
                rsi_score = 0
            score += rsi_score * 0.3
            weights += 0.3
        
        # MACD contribution
        if indicators.macd and indicators.macd_signal:
            macd_score = 1 if indicators.macd > indicators.macd_signal else -1
            if indicators.macd_histogram:
                macd_score *= min(abs(indicators.macd_histogram) / 100, 1)
            score += macd_score * 0.25
            weights += 0.25
        
        # Moving average trend
        if indicators.sma_20 and indicators.sma_50:
            ma_score = 1 if indicators.sma_20 > indicators.sma_50 else -1
            score += ma_score * 0.25
            weights += 0.25
        
        # Normalize score
        if weights > 0:
            score /= weights
        
        return max(min(score, 1), -1)  # Clamp to [-1, 1]
    
    async def _llm_analyze(
        self,
        market_data: AggregatedMarketData,
        ta_score: float,
        sentiment_score: float
    ) -> dict[str, Any]:
        """Use LLM for advanced market analysis"""
        # If no LLM configured, return basic analysis
        if not self._llm_client:
            return {
                "recommendation": "hold" if abs(ta_score) < 0.3 else ("long" if ta_score > 0 else "short"),
                "confidence": abs(ta_score),
                "reasoning": f"Technical score: {ta_score:.2f}, Sentiment: {sentiment_score:.2f}",
                "risk_assessment": "moderate"
            }
        
        # Build prompt for LLM
        prompt = self._build_analysis_prompt(market_data, ta_score, sentiment_score)
        
        try:
            # Call LLM API (placeholder - would use actual API)
            # response = await self._llm_client.chat.completions.create(...)
            
            # For now, return rule-based analysis
            return {
                "recommendation": "hold" if abs(ta_score) < 0.3 else ("long" if ta_score > 0 else "short"),
                "confidence": abs(ta_score),
                "reasoning": f"Based on technical analysis (score: {ta_score:.2f}) and market sentiment ({sentiment_score:.2f})",
                "risk_assessment": "moderate" if abs(ta_score) < 0.5 else "elevated"
            }
            
        except Exception as e:
            logger.error(f"LLM analysis failed: {e}")
            return {
                "recommendation": "hold",
                "confidence": 0.3,
                "reasoning": "Analysis unavailable",
                "risk_assessment": "unknown"
            }
    
    def _build_analysis_prompt(
        self,
        market_data: AggregatedMarketData,
        ta_score: float,
        sentiment_score: float
    ) -> str:
        """Build analysis prompt for LLM"""
        indicators = market_data.indicators
        
        prompt = f"""Analyze the following cryptocurrency market data and provide a trading recommendation.

Symbol: {market_data.symbol}
Current Price: ${float(market_data.current_price):,.2f}
24h Change: {market_data.price_change_24h:.2f}%

Technical Indicators:
- RSI (14): {indicators.rsi_14:.2f if indicators.rsi_14 else 'N/A'}
- MACD: {indicators.macd:.4f if indicators.macd else 'N/A'}
- MACD Signal: {indicators.macd_signal:.4f if indicators.macd_signal else 'N/A'}
- SMA 20: ${indicators.sma_20:,.2f if indicators.sma_20 else 'N/A'}
- SMA 50: ${indicators.sma_50:,.2f if indicators.sma_50 else 'N/A'}

Technical Score: {ta_score:.2f} (-1 bearish to 1 bullish)
Sentiment Score: {sentiment_score:.2f} (-1 negative to 1 positive)

Based on this data, provide:
1. Trading recommendation (LONG/SHORT/HOLD)
2. Confidence level (0-100%)
3. Entry price range
4. Stop loss price
5. Take profit price(s)
6. Key reasoning points
7. Risk assessment

Respond in JSON format."""

        return prompt
    
    def _create_signal(
        self,
        market_data: AggregatedMarketData,
        market_type: MarketType,
        combined_score: float,
        ta_score: float,
        sentiment_score: float,
        llm_analysis: dict
    ) -> Optional[TradingSignal]:
        """Create trading signal from analysis"""
        import uuid
        from datetime import timedelta
        
        # Determine signal type
        if combined_score > 0.3:
            signal_type = SignalType.LONG
        elif combined_score < -0.3:
            signal_type = SignalType.SHORT
        else:
            return None
        
        # Determine strength
        abs_score = abs(combined_score)
        if abs_score > 0.7:
            strength = SignalStrength.STRONG
        elif abs_score > 0.5:
            strength = SignalStrength.MODERATE
        else:
            strength = SignalStrength.WEAK
        
        # Calculate price targets
        current_price = float(market_data.current_price)
        atr = market_data.indicators.atr_14 or (current_price * 0.02)
        
        if signal_type == SignalType.LONG:
            entry_price = current_price
            stop_loss = current_price - (atr * 1.5)
            take_profit = current_price + (atr * 3)
        else:
            entry_price = current_price
            stop_loss = current_price + (atr * 1.5)
            take_profit = current_price - (atr * 3)
        
        # Calculate risk/reward
        risk = abs(entry_price - stop_loss)
        reward = abs(take_profit - entry_price)
        risk_reward = reward / risk if risk > 0 else 0
        
        # Suggested position size based on strength
        position_pct = {
            SignalStrength.STRONG: 2.0,
            SignalStrength.MODERATE: 1.0,
            SignalStrength.WEAK: 0.5
        }[strength]
        
        return TradingSignal(
            signal_id=str(uuid.uuid4()),
            timestamp=datetime.now(timezone.utc),
            symbol=market_data.symbol,
            market_type=market_type,
            signal_type=signal_type,
            strength=strength,
            confidence=llm_analysis.get("confidence", abs_score),
            reasoning=llm_analysis.get("reasoning", f"Combined score: {combined_score:.2f}"),
            entry_price=Decimal(str(round(entry_price, 2))),
            stop_loss=Decimal(str(round(stop_loss, 2))),
            take_profit=Decimal(str(round(take_profit, 2))),
            suggested_position_pct=position_pct,
            risk_reward_ratio=round(risk_reward, 2),
            valid_until=datetime.now(timezone.utc) + timedelta(hours=4),
            indicators_snapshot=market_data.indicators.to_dict(),
            market_context={
                "ta_score": ta_score,
                "sentiment_score": sentiment_score,
                "volatility_24h": market_data.volatility_24h
            }
        )
    
    async def detect_arbitrage(
        self,
        symbol: str,
        exchanges: list[str]
    ) -> Optional[ArbitrageOpportunity]:
        """Detect arbitrage opportunities across exchanges"""
        # Placeholder for arbitrage detection
        # Would compare prices across multiple exchanges
        return None
    
    def get_active_signals(self) -> list[TradingSignal]:
        """Get all active (non-expired) signals"""
        now = datetime.now(timezone.utc)
        return [
            signal for signal in self._active_signals.values()
            if signal.valid_until > now
        ]
    
    def invalidate_signal(self, signal_id: str) -> bool:
        """Invalidate/remove an active signal"""
        if signal_id in self._active_signals:
            del self._active_signals[signal_id]
            return True
        return False
